test:
	g++ -std=c++11 bitstream_ut.cpp bitstream.cpp -I ../../3rd/gtest-1.7.0/include/  ../../3rd/gtest-1.7.0/src/gtest-all.o ../../3rd/gtest-1.7.0/src/gtest_main.o -o bitstream_ut
	./bitstream_ut

clean:
	rm ./bitstream_ut
